import React from 'react'

const AboutUs = () => {
  return (
    <div>
      <h1>who are we</h1>
      <p>TAYLOR MOVERS IS A MULTINATIONAL CORPORATION HEADQUARTERED IN ATLANTA, GEORGIA U.S.A. WITH OUR EAST AFRICAN OFFICES IN NAIROBI, KENYA. WE ARE A TRANSPORTATION ENTERPRISE, SPECIALIZING IN LOGISTICS, CLEARING AND FORWARDING AND RELOCATION OF PERSONAL AND CORPORATE EFFECTS BOTH LOCALLY AND INTERNATIONALLY</p>
      <h1>what do we do`</h1>
    </div>
   
  )
}

export default AboutUs

